# FinSight — Data Overview

Initial exploration of the raw datasets used in the FinSight project.

The goal of this notebook is to:
- inspect dataset structure,
- identify data types,
- understand relationships between tables,
- detect initial data quality issues,
- prepare for the cleaning and validation stage.

In [40]:
import pandas as pd
import numpy as np
import json

print("FinSight environment ready")

FinSight environment ready

## Users dataset

In [41]:
users = pd.read_csv("../data/raw/users_data.csv")
users.head()

,id,current_age,retirement_age,birth_year,birth_month,gender,address,latitude,longitude,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards
0,825,53,66,1966,11,Female,462 Rose Lane,34.15,-117.76,$29278,$59696,$127613,787,5
1,1746,53,68,1966,12,Female,3606 Federal Boulevard,40.76,-73.74,$37891,$77254,$191349,701,5
2,1718,81,67,1938,11,Female,766 Third Drive,34.02,-117.89,$22681,$33483,$196,698,5
3,708,63,63,1957,1,Female,3 Madison Street,40.71,-73.99,$163145,$249925,$202328,722,4
4,1164,43,70,1976,9,Male,9620 Valley Stream Drive,37.76,-122.44,$53797,$109687,$183855,675,1

In [42]:
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 2000 non-null   int64
 1   current_age        2000 non-null   int64
 2   retirement_age     2000 non-null   int64
 3   birth_year         2000 non-null   int64
 4   birth_month        2000 non-null   int64
 5   gender             2000 non-null   str
 6   address            2000 non-null   str
 7   latitude           2000 non-null   float64
 8   longitude          2000 non-null   float64
 9   per_capita_income  2000 non-null   str
 10  yearly_income      2000 non-null   str
 11  total_debt         2000 non-null   str
 12  credit_score       2000 non-null   int64
 13  num_credit_cards   2000 non-null   int64
dtypes: float64(2), int64(7), str(5)
memory usage: 218.9 KB

In [43]:
users.dtypes

id                     int64
current_age            int64
retirement_age         int64
birth_year             int64
birth_month            int64
gender                   str
address                  str
latitude             float64
longitude            float64
per_capita_income        str
yearly_income            str
total_debt               str
credit_score           int64
num_credit_cards       int64
dtype: object

In [44]:
users.describe()

,id,current_age,retirement_age,birth_year,birth_month,latitude,longitude,credit_score,num_credit_cards
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,999.500000,45.391500,66.237500,1973.803000,6.439000,37.389225,-91.554765,709.734500,3.073000
std,577.494589,18.414092,3.628867,18.421234,3.565338,5.114324,16.283293,67.221949,1.637379
min,0.000000,18.000000,50.000000,1918.000000,1.000000,20.880000,-159.410000,480.000000,1.000000
25%,499.750000,30.000000,65.000000,1961.000000,3.000000,33.837500,-97.395000,681.000000,2.000000
50%,999.500000,44.000000,66.000000,1975.000000,7.000000,38.250000,-86.440000,711.500000,3.000000
75%,1499.250000,58.000000,68.000000,1989.000000,10.000000,41.200000,-80.130000,753.000000,4.000000
max,1999.000000,101.000000,79.000000,2002.000000,12.000000,61.200000,-68.670000,850.000000,9.000000

## Transactions dataset

In [45]:
transactions = pd.read_csv("../data/raw/transactions_data.csv")
transactions.head()

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors
0,7475327,2010-01-01 00:01:00,1556,2972,$-77.00,Swipe Transaction,59935,Beulah,ND,58523.0,5499,NaN
1,7475328,2010-01-01 00:02:00,561,4575,$14.57,Swipe Transaction,67570,Bettendorf,IA,52722.0,5311,NaN
2,7475329,2010-01-01 00:02:00,1129,102,$80.00,Swipe Transaction,27092,Vista,CA,92084.0,4829,NaN
3,7475331,2010-01-01 00:05:00,430,2860,$200.00,Swipe Transaction,27092,Crown Point,IN,46307.0,4829,NaN
4,7475332,2010-01-01 00:06:00,848,3915,$46.41,Swipe Transaction,13051,Harwood,MD,20776.0,5813,NaN

In [51]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 13305915 entries, 0 to 13305914
Data columns (total 12 columns):
 #   Column          Dtype
---  ------          -----
 0   id              int64
 1   date            str
 2   client_id       int64
 3   card_id         int64
 4   amount          str
 5   use_chip        str
 6   merchant_id     int64
 7   merchant_city   str
 8   merchant_state  str
 9   zip             float64
 10  mcc             int64
 11  errors          str
dtypes: float64(1), int64(5), str(6)
memory usage: 1.2 GB

In [52]:
transactions.dtypes

id                  int64
date                  str
client_id           int64
card_id             int64
amount                str
use_chip              str
merchant_id         int64
merchant_city         str
merchant_state        str
zip               float64
mcc                 int64
errors                str
dtype: object

In [53]:
transactions.describe()

,id,client_id,card_id,merchant_id,zip,mcc
count,1.330592e+07,1.330592e+07,1.330592e+07,1.330592e+07,1.165321e+07,1.330592e+07
mean,1.558402e+07,1.026812e+03,3.475268e+03,4.772376e+04,5.132782e+04,5.565440e+03
std,4.704499e+06,5.816386e+02,1.674356e+03,2.581534e+04,2.940423e+04,8.757002e+02
min,7.475327e+06,0.000000e+00,0.000000e+00,1.000000e+00,1.001000e+03,1.711000e+03
25%,1.150604e+07,5.190000e+02,2.413000e+03,2.588700e+04,2.860200e+04,5.300000e+03
50%,1.557087e+07,1.070000e+03,3.584000e+03,4.592600e+04,4.767000e+04,5.499000e+03
75%,1.965361e+07,1.531000e+03,4.901000e+03,6.757000e+04,7.790100e+04,5.812000e+03
max,2.376187e+07,1.998000e+03,6.144000e+03,1.003420e+05,9.992800e+04,9.402000e+03

## Cards dataset

In [54]:
cards = pd.read_csv("../data/raw/cards_data.csv")
cards.head()

,id,client_id,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web
0,4524,825,Visa,Debit,4344676511950444,12/2022,623,YES,2,$24295,09/2002,2008,No
1,2731,825,Visa,Debit,4956965974959986,12/2020,393,YES,2,$21968,04/2014,2014,No
2,3701,825,Visa,Debit,4582313478255491,02/2024,719,YES,2,$46414,07/2003,2004,No
3,42,825,Visa,Credit,4879494103069057,08/2024,693,NO,1,$12400,01/2003,2012,No
4,4659,825,Mastercard,Debit (Prepaid),5722874738736011,03/2009,75,YES,1,$28,09/2008,2009,No

In [55]:
cards.info()

<class 'pandas.DataFrame'>
RangeIndex: 6146 entries, 0 to 6145
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     6146 non-null   int64
 1   client_id              6146 non-null   int64
 2   card_brand             6146 non-null   str
 3   card_type              6146 non-null   str
 4   card_number            6146 non-null   int64
 5   expires                6146 non-null   str
 6   cvv                    6146 non-null   int64
 7   has_chip               6146 non-null   str
 8   num_cards_issued       6146 non-null   int64
 9   credit_limit           6146 non-null   str
 10  acct_open_date         6146 non-null   str
 11  year_pin_last_changed  6146 non-null   int64
 12  card_on_dark_web       6146 non-null   str
dtypes: int64(6), str(7)
memory usage: 624.3 KB

In [56]:
cards.dtypes

id                       int64
client_id                int64
card_brand                 str
card_type                  str
card_number              int64
expires                    str
cvv                      int64
has_chip                   str
num_cards_issued         int64
credit_limit               str
acct_open_date             str
year_pin_last_changed    int64
card_on_dark_web           str
dtype: object

In [57]:
cards.describe()

,id,client_id,card_number,cvv,num_cards_issued,year_pin_last_changed
count,6146.000000,6146.000000,6.146000e+03,6146.000000,6146.000000,6146.000000
mean,3072.500000,994.939636,4.820426e+15,506.220794,1.503091,2013.436707
std,1774.341709,578.614626,1.328582e+15,289.431123,0.519191,4.270699
min,0.000000,0.000000,3.001055e+14,0.000000,1.000000,2002.000000
25%,1536.250000,492.250000,4.486365e+15,257.000000,1.000000,2010.000000
50%,3072.500000,992.000000,5.108957e+15,516.500000,1.000000,2013.000000
75%,4608.750000,1495.000000,5.585237e+15,756.000000,2.000000,2017.000000
max,6145.000000,1999.000000,6.997197e+15,999.000000,3.000000,2020.000000

## Codes dataset

In [58]:
with open("../data/raw/mcc_codes.json", "r") as file:
    mcc_dict = json.load(file)
type(mcc_dict) 
list(mcc_dict.items())[:5]
codes = pd.DataFrame(
    mcc_dict.items(),
    columns=["mcc", "description"]
)
codes.head()

    mcc                           description
0  5812         Eating Places and Restaurants
1  5541                      Service Stations
2  7996  Amusement Parks, Carnivals, Circuses
3  5411          Grocery Stores, Supermarkets
4  4784                 Tolls and Bridge Fees

In [59]:
codes.info()

<class 'pandas.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   mcc          109 non-null    str
 1   description  109 non-null    str
dtypes: str(2)
memory usage: 1.8 KB

In [60]:
codes.dtypes

mcc            str
description    str
dtype: object

In [61]:
codes.describe()

         mcc         description
count    109                 109
unique   109                 108
top     5812  Passenger Railways
freq       1                   2

## Fraud labels dataset

In [62]:
with open("../data/raw/train_fraud_labels.json", "r") as file:
    fraud_dict = json.load(file)
type(fraud_dict)
list(fraud_dict.items())[:5]
fraud_target = fraud_dict["target"]
type(fraud_target)
fraud = pd.DataFrame(
    fraud_target.items(),
    columns=["transaction_id", "is_fraud"]
)
fraud.head()

  transaction_id is_fraud
0       10649266       No
1       23410063       No
2        9316588       No
3       12478022       No
4        9558530       No

In [63]:
fraud.shape

(8914963, 2)

In [64]:
fraud["is_fraud"].value_counts()

is_fraud
No     8901631
Yes      13332
Name: count, dtype: int64

In [65]:
fraud.info()

<class 'pandas.DataFrame'>
RangeIndex: 8914963 entries, 0 to 8914962
Data columns (total 2 columns):
 #   Column          Dtype
---  ------          -----
 0   transaction_id  str
 1   is_fraud        str
dtypes: str(2)
memory usage: 136.0 MB

In [66]:
fraud.dtypes

transaction_id    str
is_fraud          str
dtype: object

In [67]:
fraud.describe()

       transaction_id is_fraud
count         8914963  8914963
unique        8914963        2
top          10649266       No
freq                1  8901631