In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine

In [6]:
load_dotenv()

engine = create_engine(
    f"postgresql+psycopg2://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}"
    f"@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)

In [7]:
with engine.connect() as connection:
    print("Connected!")

Connected!

In [6]:
query = """
select
    min(transaction_timestamp) as min_date,
    max(transaction_timestamp) as max_date,
    count(*) as number_of_transactions
from analytics.fraud_ml_features
"""

dataset_info = pd.read_sql(query, engine)

dataset_info

             min_date            max_date  number_of_transactions
0 2010-01-01 00:01:00 2019-10-31 23:57:00                 8914963

In [7]:
query = """
select
    extract(year from transaction_timestamp)::int as year,
    count(*) as transactions,
    count(*) filter (where is_fraud = true) as fraud_transactions,
    round(
        count(*) filter (where is_fraud = true)::numeric
        / count(*) * 100,
        4
    ) as fraud_rate
from analytics.fraud_ml_features
group by extract(year from transaction_timestamp)
order by year
"""

fraud_by_year = pd.read_sql(query, engine)

fraud_by_year

   year  transactions  fraud_transactions  fraud_rate
0  2010        831529                2573      0.3094
1  2011        863428                  37      0.0043
2  2012        885421                 923      0.1042
3  2013        907304                1337      0.1474
4  2014        915073                 664      0.0726
5  2015        930224                2189      0.2353
6  2016        932762                2448      0.2624
7  2017        937284                 172      0.0184
8  2018        934599                1629      0.1743
9  2019        777339                1360      0.1750